name: fof_dashboard

channels:
  - defaults
  # - conda-forge

dependencies:
  - python>=3.9
  - numpy
  - netcdf4
  - xarray
  - pandas
  - matplotlib
  - altair
  - streamlit
  - pip
  - pip:
    - fair==1.6.4
    - git+https://github.com/FixOurFood/AgriFoodPy-light.git@main
