name: fof_dashboard

channels:
  - conda-forge
  - defaults

dependencies:
  - numpy
  - netcdf4
  - xarray
  - pandas
  - matplotlib
  - altair
  - streamlit
  - pip
  - pip:
    - fair
    # - git+git://github.com/jucordero/AgriFoodPy@refactor_examples
