name: fof_dashboard

channels:
  - defaults
  # - conda-forge

dependencies:
  - python>=3.9
  - numpy
  - netcdf4
  - xarray
  - pandas
  - matplotlib
  - altair
  - streamlit
  - pip
  - pip:
    - millify
    - fair
    - -e git+https://github.com/FixOurFood/AgriFoodPy.git@streamlit_dashboard#egg=agrifoodpy
    - streamlit-modal
